### ISSUE TITLE
auto main() -> int

### ISSUE THREAD

**Issue by dan-42** [nxxm/nxxm#2]
When I use the modern style for function:
```cpp
auto main() -> int{}
```
instead of the old style 
```cpp
int main(){}
```
nxxm want to generate a library and not an executable.

**Comment by daminetreg** [comment]
Hi @dan-42 :grinning: 

Thanks for notifying this. Indeed there are some issues for the moment with non-old-style main. 

Some of those were fixed but still working on it. I didn't had a test case for this specific one.

Fixes for this will be released this month.

**Comment by daminetreg** [comment]
Dear @dan-42 this has been fixed and we have test cases now for it, so there won't be any regressions on this anymore.

It is available as [release v0.0.7](https://github.com/nxxm/nxxm/releases/tag/v0.0.7).

You can simply upgrade it from your current nxxm install : `nxxm --force-upgrade` or if you didn't start the tool in the last 24 hours you will be notified for the new release.

Don't hesitate to confirm it is fixed for you here.

**Comment by daminetreg** [comment]
I close the issue, but don't hesitate to reopen if it still doesn't work for you.
