### ISSUE TITLE
nxxm behind corporate proxy

### ISSUE THREAD

**Issue by mbodmer** [nxxm/nxxm#4]
Hi.
Is it possible to tell nxxm to use a http proxy?
It does  not seem to respect the $http_proxy, $https_proxy and $no_proxy environment variables on linux.

The get-started example looks like this:
```
system:111: Connection refused distilled into : 2
shipping cmake.
⏳ { ●●●         }system:111: Connection refused distilled into : 2
● [err] [https://nxxm.github.io/distro/cmake/cmake-3.12.1-Linux-x86_64.zip]: Download error ( i.e. error:2 CONNECTION_FAILURE ), retrying 5 times.
system:111: Connection refused distilled into : 2
● [err] [https://nxxm.github.io/distro/cmake/cmake-3.12.1-Linux-x86_64.zip]: Download error ( i.e. error:2 CONNECTION_FAILURE ), retrying 4 times.
system:111: Connection refused distilled into : 2
● [err] [https://nxxm.github.io/distro/cmake/cmake-3.12.1-Linux-x86_64.zip]: Download error ( i.e. error:2 CONNECTION_FAILURE ), retrying 3 times.
system:111: Connection refused distilled into : 2
● [err] [https://nxxm.github.io/distro/cmake/cmake-3.12.1-Linux-x86_64.zip]: Download error ( i.e. error:2 CONNECTION_FAILURE ), retrying 2 times.
⏳ {  ●●●        }system:111: Connection refused distilled into : 2
● [err] [https://nxxm.github.io/distro/cmake/cmake-3.12.1-Linux-x86_64.zip]: Download error ( i.e. error:2 CONNECTION_FAILURE ), retrying 1 times.
system:111: Connection refused distilled into : 2
⏳ ● [err] shipping cmake.
● [err] Dynamic exception type: std::runtime_error
std::exception::what: [https://nxxm.github.io/distro/cmake/cmake-3.12.1-Linux-x86_64.zip]: Download error ( i.e. error:2 CONNECTION_FAILURE ). status code: 0

● [err] Dynamic exception type: std::runtime_error
std::exception::what: Impossible to ship cmake
```

**Comment by daminetreg** [comment]
Hi @mbodmer,

Thank you for using nxxm and for taking the time to report about your issues or problems with it. :smile: 

Happily you are on linux and there is a workaround, but indeed usual http_proxy/https_proxy environment variables are not supported. 

It's on the Roadmap though. This should be in the release of beginning of January.

In the meantime the following workaround can be used [with this python script](https://github.com/n1nj4sec/pr0cks) which transforms your corporate SOCKS or HTTP proxy in a transparent one. Then any TCP or DNS connection done on your machine will be transparently proxied. Which makes nxxm run.

To set it up and be able to run nxxm over this proxy connection  :
* Copy the following in a shell script named `transparently-proxy` on your machine
* Edit the first 4 lines according to your corporate proxy settings
* Run the script by running `source transparently-proxy` or `chmod +x  transparently-proxy; ./ transparently-proxy`.

```bash
#!/bin/bash

PROXY_DNS="your.proxy.com" # Here the hostname / domain name of your corporate proxy
PROXY_PORT="8080" # The Proxy port 
PROXY_TYPE="SOCKS5" # or "SOCKS4" or "HTTP"
NETWORK_INTERFACE="eth0"

PROXY_IP=`host ${PROXY_DNS} | cut -d" " -f4`
sudo apt-get update 
sudo apt-get -y install python-pip git
sudo pip install dnslib
git clone https://github.com/n1nj4sec/pr0cks.git
    
sudo iptables -t nat -A OUTPUT -o ${NETWORK_INTERFACE} -p tcp -m tcp ! -d ${PROXY_IP} -j REDIRECT --to-ports 10080
sudo iptables -t nat -A OUTPUT -o ${NETWORK_INTERFACE} -p udp -m udp --dport 53 -j REDIRECT --to-ports 1053

cd pr0cks && python pr0cks.py --proxy ${PROXY_TYPE}:${PROXY_IP}:${PROXY_PORT}
```

With the hope that it is possible for you to use this workaround for the moment.

Support for the http_proxy, https_proxy environment variables will be added when our team or an opensource contributor will add the support to [xxhr](https://github.com/nxxm/xxhr) the underlying http(s) library of nxxm. We will work on it by end of december but if anyone tackles it before us, it will be available sooner.

Warm regards

**Comment by mbodmer** [comment]
Hi Damien, thanks for your time. Your proposal looks good, I will try this. Regards, Marc

**Comment by daminetreg** [comment]
Closing as the workaround is usable as of now.
